name: "Worflow for provisioning infra using terraform for bankflow application"
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
      - "develop"
jobs:

  infra-setup:

    runs-on: ["ubuntu-latest"]

    steps:

    # Performs code checkout to get all the required files
    - name: "Code Checkout"
      uses: "actions/checkout@v4"

    # Configures the aws credentials for the authentication
    - name: "Configure AWS credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    # Sets up terraform in the runner
    - name: "Install Terraform"
      uses: hashicorp/setup-terraform@v3

    # Initializes the Terraform working directory, downloading provider plugins and setting up the backend.
    - name: "Execute Terraform Init"
      run: terraform init

    # Validates the terraform file configurations
    - name: "Validate Terraform Configurations"
      run: terraform validate

    # View Terraform Plan
    - name: "View Terraform Plan"
      run: terraform plan -auto-approve -var-file="dev.params.tfvars"

    - name: "Execute Terraform apply"
      if: github.event_name == 'push' && github.ref_name == 'main'
      run: "echo Terraform apply"